### ISSUE TITLE
Arquivo Remessa CNAB 400 Santander

### ISSUE THREAD

**Issue by PedroFilipeDeMoraisLima** [BoletoNet/boletonet#576]
Estou gerando o arquivo de remessa CNAB 400 Santander e estou obtendo o seguinte erro:

Message: Input string was not in a correct format.

at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at BoletoNet.Banco_Santander.Mod11Santander(String seq, Int32 lim)
   at BoletoNet.Banco_Santander.GerarDetalheRemessaCNAB400(Boleto boleto, Int32 numeroRegistro, TipoArquivo tipoArquivo)

Segue trecho do código:

boletoBancario.Boleto = Boleto;
boletoBancario.MostrarCodigoCarteira = true;

boletoBancario.Boleto.NossoNumero = "0000001";
boletoBancario.Boleto.Valida();
boletoBancario.MostrarComprovanteEntrega = (Request.Url.Query == "?show");
Cedente.CodigoTransmissao = "30070868338701300457";

Boletos objBOLETOS = new Boletos();
objBOLETOS.Add(Boleto);

                using (var memoryStr = new MemoryStream())
                {
                    var objREMESSA = new ArquivoRemessa(TipoArquivo.CNAB400);

                    string MensagemOut = string.Empty;
                    objREMESSA.ValidarArquivoRemessa(Patio.CodigoBeneficiario, new Banco(CodigoBanco), Cedente, objBOLETOS, 1, out MensagemOut);

                    objREMESSA.GerarArquivoRemessa(Patio.CodigoBeneficiario, new Banco(CodigoBanco), Cedente, objBOLETOS, memoryStr, 1);

                  
                }
                
            }

**Comment by dieggop** [comment]
Tu implantou o CNAB400 do Santander?

**Comment by PedroFilipeDeMoraisLima** [comment]
Estou no processo de validação com o banco.

**Comment by PedroFilipeDeMoraisLima** [comment]
Recebi o seguinte retorno do banco:


Registro inválido na linha 2. O tamanho do registro deve ser de   400 posições.
--
Campo inválido na linha 2. Tipo de registro [Registro de   Movimento]. O campo [Complemento], posição 384 a 385, deve ser [77 (conta   cobrança 130045777) Definido em Cadastro > Empresas]. Valor atual [7 ].
Campo inválido na linha 2. Tipo de registro [Registro de   Movimento]. O campo [Número de dias para protesto], posição 392 a 393, deve   ser [Numérico, alinhado à direita, preenchido com zeros à esquerda, sem   máscara de edição (ponto, vírgula, barra)]. Valor atual [0 ].
Campo inválido na linha 2. Tipo de registro [Registro de   Movimento]. O campo [Branco], posição 394 a 394, deve ser [Brancos]. Valor   atual [0].
Campo inválido na linha 2. Tipo de registro [Registro de   Movimento]. O campo [Número seqüencial do registro], posição 395 a 400, deve   ser [000002]. Valor atual [00002].

Alguém pode me ajudar?

**Comment by leopipolo** [comment]
Eu vi na página da versão Boleto2Net que o Santander está como homologado. Quer dizer que o arquivo remessa gerado para o Santander com a Boleto2Net está sendo aceito pelo banco, enquanto que o da BoletoNet não está sendo aceito com esses erros?

**Comment by alexsandersalinas** [comment]
Ola, você já resolveu o problema com o Santander.. estou conseguindo gerar normalmente.

**Comment by leopipolo** [comment]
@alexsandersalinas eu acabei decidindo usar a Boleto2Net e estou conseguindo gerar normalmente com ela para Itaú e Santander.

**Comment by alexsandersalinas** [comment]
OK, obrigado pelo retorno.. estou com a versão homologada funcionando para o Santander e Itau também.

**Comment by luxu** [comment]
@alexsandersalinas vc poderia me fornecer sua solução pq aqui está dando os seguintes erros:

## **Esses campos são gerados onde?**

Campo inválido na linha 2. Tipo de registro [Registro de Movimento]. O campo [Número seqüencial do registro], posição 395 a 400, deve ser [000002]. Valor atual [ 00000].
Campo inválido na linha 3. Tipo de registro [Trailler de Arquivo]. O campo [Quantidade de documentos no arquivo], posição 2 a 7, deve ser [000001]. Valor atual [000005].
Campo inválido na linha 3. Tipo de registro [Trailler de Arquivo]. O campo [Valor total dos títulos], posição 8 a 20, deve ser [0000000007000]. Valor atual [0000000000020].
Registro inválido na linha 3. O registro está fora de ordem.

## **(Pelo q vi já gera em A4, mas como posso ter certeza?)**

OBS: Altere o formado do boleto PDF para A4 para que possamos analisar.
